$(function(){
    $('.black').click(function(){
        $('#black').css('display','block');
        $('.bl-title').css('display','block');
        $('#ml').css('display','none');
        $('.ml-title').css('display','none');
        $('#burgundy').css('display','none');
        $('.bu-title').css('display','none');
        $('#rain').css('display','none');
        $('.r-title').css('display','none');
        $('#steel').css('display','none');
        $('.s-title').css('display','none');
        $('#wc').css('display','none');
        $('.wc-title').css('display','none');
        $('.black').css('opacity',1);
        $('.ml,.burgundy,.rain,.steel,.wc').css('opacity',0.5);
    });
    $('.ml').click(function(){
        $('#ml').css('display','block');
        $('.ml-title').css('display','block');
        $('#black').css('display','none');
        $('.bl-title').css('display','none');
        $('#burgundy').css('display','none');
        $('.bu-title').css('display','none');
        $('#rain').css('display','none');
        $('.r-title').css('display','none');
        $('#steel').css('display','none');
        $('.s-title').css('display','none');
        $('#wc').css('display','none');
        $('.wc-title').css('display','none');
        $('.ml').css('opacity',1);
        $('.black,.burgundy,.rain,.steel,.wc').css('opacity',0.5);
    });
    $('.burgundy').click(function(){
        $('#burgundy').css('display','block');
        $('.bu-title').css('display','block');
        $('#black').css('display','none');
        $('.bl-title').css('display','none');
        $('#ml').css('display','none');
        $('.ml-title').css('display','none');
        $('#rain').css('display','none');
        $('.r-title').css('display','none');
        $('#steel').css('display','none');
        $('.s-title').css('display','none');
        $('#wc').css('display','none');
        $('.wc-title').css('display','none');
        $('.burgundy').css('opacity',1);
        $('.black,.ml,.rain,.steel,.wc').css('opacity',0.5);
    });
    $('.rain').click(function(){
        $('#rain').css('display','block');
        $('.r-title').css('display','block');
        $('#black').css('display','none');
        $('.bl-title').css('display','none');
        $('#ml').css('display','none');
        $('.ml-title').css('display','none');
        $('#burgundy').css('display','none');
        $('.bu-title').css('display','none');
        $('#steel').css('display','none');
        $('.s-title').css('display','none');
        $('#wc').css('display','none');
        $('.wc-title').css('display','none');
        $('.rain').css('opacity',1);
        $('.black,.ml,.burgundy,.steel,.wc').css('opacity',0.5);
    });
    $('.steel').click(function(){
        $('#steel').css('display','block');
        $('.s-title').css('display','block');
        $('#black').css('display','none');
        $('.bl-title').css('display','none');
        $('#ml').css('display','none');
        $('.ml-title').css('display','none');
        $('#burgundy').css('display','none');
        $('.bu-title').css('display','none');
        $('#rain').css('display','none');
        $('.r-title').css('display','none');
        $('#wc').css('display','none');
        $('.wc-title').css('display','none');
        $('.steel').css('opacity',1);
        $('.black,.ml,.burgundy,.rain,.wc').css('opacity',0.5);
    });
    $('.wc').click(function(){
        $('#wc').css('display','block');
        $('.wc-title').css('display','block');
        $('#black').css('display','none');
        $('.bl-title').css('display','none');
        $('#ml').css('display','none');
        $('.ml-title').css('display','none');
        $('#burgundy').css('display','none');
        $('.bu-title').css('display','none');
        $('#rain').css('display','none');
        $('.r-title').css('display','none');
        $('#steel').css('display','none');
        $('.s-title').css('display','none');
        $('.wc').css('opacity',1);
        $('.black,.ml,.burgundy,.rain,.steel').css('opacity',0.5);
    });

});


$(document).ready(function() {
    $('#fullpage').fullpage({

    });
});

$(function(){
    $('.right-img1').mouseover(function(){
       $('.bg1').css('display','block');
       $('.img1-sub').css('display','block');
    });
    $('.right-img1').mouseleave(function(){
        $('.img1-sub').css('display','none');
        $('.bg1').css('display','none');
     });
     $('.right-img2').mouseover(function(){
        $('.img2-sub').css('display','block');
        $('.bg2').css('display','block');
     });
     $('.right-img2').mouseleave(function(){
         $('.img2-sub').css('display','none');
         $('.bg2').css('display','none');
      });
      $('.right-img3').mouseover(function(){
        $('.img3-sub').css('display','block');
        $('.bg3').css('display','block');
     });
     $('.right-img3').mouseleave(function(){
         $('.img3-sub').css('display','none');
         $('.bg3').css('display','none');
      });
      $('.right-img4').mouseover(function(){
        $('.img4-sub').css('display','block');
        $('.bg4').css('display','block');
     });
     $('.right-img4').mouseleave(function(){
         $('.img4-sub').css('display','none');
         $('.bg4').css('display','none');
      });
      $('.right-img5').mouseover(function(){
        $('.img5-sub').css('display','block');
        $('.bg5').css('display','block');
     });
     $('.right-img5').mouseleave(function(){
         $('.img5-sub').css('display','none');
         $('.bg5').css('display','none');
      });
      $('.right-img6').mouseover(function(){
        $('.img6-sub').css('display','block');
        $('.bg6').css('display','block');
     });
     $('.right-img6').mouseleave(function(){
         $('.img6-sub').css('display','none');
         $('.bg6').css('display','none');
      });
      $('.right-img7').mouseover(function(){
        $('.img7-sub').css('display','block');
        $('.bg7').css('display','block');
     });
     $('.right-img7').mouseleave(function(){
         $('.img7-sub').css('display','none');
         $('.bg7').css('display','none');
      });
      $('.right-img8').mouseover(function(){
        $('.img8-sub').css('display','block');
        $('.bg8').css('display','block');
     });
     $('.right-img8').mouseleave(function(){
         $('.img8-sub').css('display','none');
         $('.bg8').css('display','none');
      });
});